import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { Eye, EyeOff, Plus, Trash2, UserRound, Lock, LogOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/hooks/use-auth";
import { useLogout } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";

const API = "https://pulse-api.joeldavidengelman.workers.dev";
const ACCOUNTS_KEY = "pulse-saved-accounts";
function savedAccounts(): string[] { try { return JSON.parse(localStorage.getItem(ACCOUNTS_KEY) || "[]"); } catch { return []; } }

export default function Settings() {
  const { user } = useAuth(); const [, setLocation] = useLocation(); const logout = useLogout(); const queryClient = useQueryClient();
  const [accounts, setAccounts] = useState<string[]>([]);
  const [current, setCurrent] = useState(""); const [newPassword, setNewPassword] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [showCurrent, setShowCurrent] = useState(false); const [showNew, setShowNew] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { const list = savedAccounts(); if (user?.username && !list.includes(user.username)) { list.unshift(user.username); localStorage.setItem(ACCOUNTS_KEY, JSON.stringify(list.slice(0, 8))); } setAccounts(list); setCurrent(user?.username || ""); }, [user?.username]);
  const remove = (name: string) => { const list = accounts.filter(x => x.toLowerCase() !== name.toLowerCase()); setAccounts(list); localStorage.setItem(ACCOUNTS_KEY, JSON.stringify(list)); };
  const switchAccount = async (name: string) => { if (name.toLowerCase() === user?.username?.toLowerCase()) return; logout.mutate(undefined, { onSuccess: () => { queryClient.clear(); setLocation(`/login?username=${encodeURIComponent(name)}`); } }); };
  const addAccount = () => setLocation("/login?add=1");
  const changePassword = async (e: React.FormEvent) => { e.preventDefault(); setError(""); setMessage(""); if (newPassword.length < 6) { setError("New password must be at least 6 characters."); return; } setBusy(true); try { const r = await fetch(`${API}/api/auth/change-password`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || "Couldn't change password."); setCurrentPassword(""); setNewPassword(""); setMessage("Password changed successfully."); } catch (e:any) { setError(e.message || "Couldn't change password."); } finally { setBusy(false); } };
  return <div className="w-full h-full overflow-y-auto custom-scrollbar"><div className="max-w-2xl mx-auto px-4 py-8"><h1 className="text-3xl font-bold">Settings</h1><p className="text-muted-foreground mt-1 mb-7">Manage your Pulse account and security.</p>
    <section className="bg-card border border-border rounded-2xl p-5 mb-5"><div className="flex items-center gap-3 mb-4"><div className="p-2 rounded-xl bg-primary/10 text-primary"><UserRound className="w-5 h-5"/></div><div><h2 className="font-semibold">Accounts</h2><p className="text-xs text-muted-foreground">Keep multiple Pulse accounts on this device.</p></div></div><div className="space-y-2">{accounts.map(name=><div key={name} className="flex items-center gap-3 p-3 rounded-xl bg-secondary/50"><div className="w-9 h-9 rounded-full bg-primary/10 grid place-items-center text-primary"><UserRound className="w-4 h-4"/></div><div className="flex-1"><p className="font-medium">@{name}</p>{name.toLowerCase()===current.toLowerCase()&&<p className="text-[11px] text-primary">Current account</p>}</div>{name.toLowerCase()!==current.toLowerCase()&&<Button variant="outline" size="sm" onClick={()=>switchAccount(name)}>Switch</Button>}<button onClick={()=>remove(name)} title="Remove saved account" className="p-2 rounded-lg text-muted-foreground hover:text-destructive hover:bg-destructive/10"><Trash2 className="w-4 h-4"/></button></div>)}</div><Button className="mt-4" variant="outline" onClick={addAccount}><Plus className="w-4 h-4 mr-2"/>Add another account</Button></section>
    <section className="bg-card border border-border rounded-2xl p-5"><div className="flex items-center gap-3 mb-4"><div className="p-2 rounded-xl bg-primary/10 text-primary"><Lock className="w-5 h-5"/></div><div><h2 className="font-semibold">Password</h2><p className="text-xs text-muted-foreground">Change your password securely. Your existing password is never displayed.</p></div></div><form onSubmit={changePassword} className="space-y-3"><div className="relative"><Input type={showCurrent?"text":"password"} value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Current password" required/><button type="button" onClick={()=>setShowCurrent(x=>!x)} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-muted-foreground">{showCurrent?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div><div className="relative"><Input type={showNew?"text":"password"} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="New password" minLength={6} required/><button type="button" onClick={()=>setShowNew(x=>!x)} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-muted-foreground">{showNew?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div>{error&&<p className="text-sm text-destructive">{error}</p>}{message&&<p className="text-sm text-green-500">{message}</p>}<Button type="submit" disabled={busy}>{busy?"Changing…":"Change password"}</Button></form></section>
    <Link href="/profile" className="inline-flex items-center gap-2 mt-5 text-sm text-primary hover:underline"><LogOut className="w-4 h-4 rotate-180"/>Back to profile</Link>
  </div></div>;
}
